Ensure SM exits if primary restore fails; and waiting SMs exit if the initial restore SM fails.

diff --git a/stable/database/files/nuosm b/stable/database/files/nuosm
--- a/stable/database/files/nuosm
+++ b/stable/database/files/nuosm
@@ -39,6 +39,11 @@ export NUOCMD DB_NAME
 function die() {
   # cleanup
   $NUOCMD set value --key $first_req --value '' --expected-value $HOSTNAME
+  $NUOCMD set value --key $startup_key/$DB_NAME --value '' --expected-value $HOSTNAME
+
+  # release my archive if it is locked
+  locked_archive=$( $NUOCMD show archives --db-name $DB_NAME --removed --removed-archive-format "archive-id: {id}" | sed -En "/^archive-id: / {N; /$HOSTNAME/ s/^archive-id: ([0-9]+).*$/\1/; T; p}" | head -n 1 )
+  [ -n "$locked_archive" ] && $NUOCMD create archive --db-name $DB_NAME --archive-path $DB_DIR --is-external --restored --archive-id $locked_archive
 
   retval=$1
   shift
@@ -55,15 +60,17 @@ function perform_restore() {
   error=
 
   # bail out early if the restore will obviously fail
-  if [ -z "$( echo $restore_source | grep '^[a-z]\+:/[^ ]\+')" ]; then
-    [ -d "$NUODB_BACKUPDIR/$restore_source" ] || error="Backupset $restore_source cannot be found in $NUODB_BACKUPDIR"
+  if [ -z "$( echo $restore_source | grep '^[a-z]\+:/[^ ]\+')" ] && [ ! -d "$NUODB_BACKUPDIR/$restore_source" ]; then
+      error="Backupset $restore_source cannot be found in $NUODB_BACKUPDIR"
+      retval=-1
+      return $retval
   fi
 
   # work out available space
   archSize="$(du -s $DB_DIR | grep -o '^ *[0-9]\+')"
   archSpace="$(df --output=avail $DB_DIR | grep -o ' *[0-9]\+')"
 
-  if [ $(( archSize * 2 < archSpace)) ]; then
+  if [ $(( archSpace > archSize * 2)) ]; then
     saveName=$DB_DIR-save-$( date +%Y%m%dT%H%M%S )
     mv $DB_DIR $saveName
      
@@ -71,6 +78,7 @@ function perform_restore() {
     if [ $retval -ne 0 ]; then
       mv $saveName $DB_DIR
       error="Error moving archive in preparation for restore"
+      return $retval
     fi
   else
     tarfile=$DB_DIR-$( date +%Y%m%dT%H%M%S ).tar.gz
@@ -80,6 +88,7 @@ function perform_restore() {
     if [ $retval -ne 0 ]; then
       rm -rf $tarfile
       error="Restore: unable to save existing archive to TAR file"
+      return $retval
     fi
 
     archSpace="$(df --output=avail $DB_DIR | grep -o ' *[0-9]\+')"
@@ -87,6 +96,7 @@ function perform_restore() {
       rm -rf $tarfile
       retval=-1
       error="Insufficient space for restore after archive has been saved to TAR."
+      return $retval
     fi
 
     rm -rf $DB_DIR
@@ -103,6 +113,13 @@ function perform_restore() {
   if [ -n "$( echo $restore_source | grep '^[a-z]\+:/[^ ]\+')" ]; then
     echo "curl -k --user '**' $restore_source | tar xzf - --strip-components $strip_levels -C $DB_DIR"
     curl -k --user "$restore_credentials" $restore_source | tar xzf - --strip-components $strip_levels -C $DB_DIR
+
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      rm -rf $DB_DIR
+      error="Restore: unable to download/unpack backup $restore_source"
+      return $retval
+    fi
 
     chown -R $(echo "${NUODB_OS_USER:-1000}:${NUODB_OS_GROUP:-0}" | tr -d '"') $DB_DIR
   else
@@ -250,13 +267,18 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
   fi
 
   # wait until it's my turn to startup
+  retry=0
   until owner=$( $NUOCMD get value --key $startup_key/$DB_NAME ); [ "$owner" = "$HOSTNAME" -o "$NUODB_SEQUENCE_SYNC" = "false" ] ; do
+
+    [ -z "$owner" -a $retry -gt 0] && die -1 "Fatal error in database RESTORE - initial SM has exited with error - aborting"
 
     # find the start-id of the SM that owns the semaphore
     owner_id=$( $NUOCMD show database --db-name $DB_NAME --skip-exited --process-format "{engine_type}: {address} start-id: {start_id};" | grep -E "^ *SM: $owner" | grep -Eo "start-id: [[0-9]+" | grep -Eo "[0-9]+")
     if [ -z "$owner_id" ]; then
       echo "Could not find start-id for starting SM on $owner - retrying..."
       sleep 30
+
+      retry=$((retry + 1))
       continue
     fi
 
@@ -277,7 +299,7 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
 fi
 
 # release my archive if it is locked
-# this will likely never execute but has been left in for completeness
+# this will likely never execute but is kept to be sure, to be sure...
 locked_archive=$( $NUOCMD show archives --db-name $DB_NAME --removed --removed-archive-format "archive-id: {id}" | sed -En "/^archive-id: / {N; /$HOSTNAME/ s/^archive-id: ([0-9]+).*$/\1/; T; p}" | head -n 1 )
 [ -n "$locked_archive" ] && $NUOCMD create archive --db-name $DB_NAME --archive-path $DB_DIR --is-external --restored --archive-id $locked_archive
 
